pipeline:
  name: TestinDotNetapplication
  identifier: TestinDotNetapplication
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: DotnetsampleApplication
        build: <+input>
  stages:
    - stage:
        name: Git Clone
        identifier: Git_Clone
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Docker Image
                  identifier: Build_Docker_Image
                  spec:
                    shell: Sh
                    command: |-
                      docker build -t harish2195/dockerwebapi:${BuildNumber} -f Dockerfile .
                      docker images
                      pwd
              - step:
                  type: Run
                  name: Push Docker image to Dockerhub
                  identifier: Push_Docker_image_to_Dockerhub
                  spec:
                    shell: Sh
                    command: |-
                      #docker login --username ${secrets.getValue("Dockerusername")} --password ${secrets.getvalue("Dockerpassword")}
                      docker login -u harish2195 -p ${DOCKER_PASSWORD}
                      docker push harish2195/dockerwebapi:${BuildNumber}
        variables:
          - name: BuildNumber
            type: String
            description: ""
            required: true
            value: <+input>
          - name: DOCKER_PASSWORD
            type: Secret
            description: ""
            required: false
            value: Dockerpassword
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: TestingUI
          environment:
            environmentRef: Dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: EKS_deployment
          execution:
            steps:
              - step:
                  type: K8sDryRun
                  name: K8sDryRun_1
                  identifier: K8sDryRun_1
                  spec: {}
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
