pipeline:
  name: TestinDotNetapplication
  identifier: TestinDotNetapplication
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: DotnetsampleApplication
        build: <+input>
  stages:
    - stage:
        name: Git Clone
        identifier: Git_Clone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Docker Image
                  identifier: Build_Docker_Image
                  spec:
                    shell: Sh
                    command: |-
                      docker build -t dockerwebapi -f Dockerfile .
                      docker images
                      pwd
              - step:
                  type: Run
                  name: Push Docker image to Dockerhub
                  identifier: Push_Docker_image_to_Dockerhub
                  spec:
                    shell: Sh
                    command: |-
                      docker login --username harish2195 --password-stdin ${DockerPassword}
                      docker push harish2195/dockerwebapi:latest
  variables:
    - name: DockerPassword
      type: String
      description: ""
      required: false
      value: manu@2195
