apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetwebapp
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dotnetwebapp
  template:
    metadata:
      name: dotnetwebapppod
      labels:
        app: dotnetwebapp
    spec:
      containers:
        - name: dotnetwebappcontainer
          image: harish2195/dockerwebapi:3.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetwebappsvc
spec:
  selector:
    app: dotnetwebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
